# Generated by Django 5.0.6 on 2025-03-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('bolum_baskani', 'Bölüm Başkanı'), ('bolum_sekreteri', 'Bölüm Sekreteri'), ('akademisyen', 'Akademisyen'), ('ogrenci', 'Öğrenci')], max_length=20, null=True),
        ),
    ]
