# Generated by Django 5.0.6 on 2025-03-26 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=10, unique=True)),
                ('ad', models.CharField(max_length=100)),
                ('kredi', models.IntegerField()),
                ('bolum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Derslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True)),
                ('kapasite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DersProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma')], max_length=10)),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.ders')),
                ('derslik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.derslik')),
                ('ogretim_elemani', models.ForeignKey(limit_choices_to={'role': 'akademisyen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ders', 'gun', 'baslangic_saati')},
            },
        ),
    ]
