# Generated by Django 5.0.6 on 2025-04-02 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_ders_ogrenci_sayisi_sinavprogrami'),
    ]

    operations = [
        migrations.CreateModel(
            name='OturmaPlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.IntegerField()),
                ('ogrenci', models.ForeignKey(limit_choices_to={'role': 'ogrenci'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.sinavprogrami')),
            ],
        ),
    ]
