# Generated by Django 5.0.6 on 2025-05-24 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_oturmaplani'),
    ]

    operations = [
        migrations.CreateModel(
            name='DersProgramiYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.dersprogrami')),
                ('yazar', models.ForeignKey(limit_choices_to={'role': 'akademisyen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnaylanmisDersProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma')], max_length=10)),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('onay_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.ders')),
                ('derslik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.derslik')),
                ('ogretim_elemani', models.ForeignKey(limit_choices_to={'role': 'akademisyen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
