# Generated by Django 5.0.6 on 2025-05-25 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_dersprogramiyorum_onaylanmisdersprogrami'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnaylanmisSinavProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.ders')),
                ('derslik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.derslik')),
                ('gozetmen', models.ForeignKey(blank=True, limit_choices_to={'role': 'akademisyen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
