# Generated by Django 5.0.6 on 2025-05-27 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0007_onaylanmissinavprogrami'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinavYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.sinavprogrami')),
                ('yazar', models.ForeignKey(limit_choices_to={'role': 'akademisyen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
