# Generated by Django 5.0.6 on 2025-06-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0008_sinavyorum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oturmaplani',
            unique_together={('sinav', 'ogrenci')},
        ),
    ]
